version: "3.8"
services:

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  consul:
    image: hashicorp/consul
    ports:
      - 8500:8500
    volumes:
      - consul_data:/consul/data

  youtube_service:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - redis
      - consul
volumes:
  redis_data:
  consul_data: